spring:
  application:
    name: notify.svc
    version: v1
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.woven.notify: DEBUG
server:
  port: 8080
  servlet:
    context-path: /api/${spring.application.version}/${spring.application.name}

